version: "3.8"

services:
  backend:
    build: .
    command: bash -c "python manage.py migrate && python  manage.py collectstatic --noinput && gunicorn --bind :8000 --workers=1 --threads=4 --timeout=120 --worker-class=gthread form_builder.wsgi --reload"
    volumes:
      - .:/code
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env

  celery:
    build: .
    command: bash -c "celery -A form_builder worker -l info -B"  
    volumes:
      - .:/code
    depends_on:
      - rabbitmq
      - backend
    env_file:
      - .env

  redis:
    image: redis:7.2.1-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./data/redis:/data
  
  rabbitmq:
    image: rabbitmq:3.13.0-management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
      - ./logs/rabbitmq:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./form_builder/static:/code/form_builder/static
      - ./form_builder/media:/code/form_builder/media
    depends_on:
      - backend